CREATE TABLE [dbo].[NumeroComanda](
   [idNumeroComada] [int] IDENTITY(1,1) NOT NULL,

CONSTRAINT [PK_NumeroComanda] PRIMARY KEY CLUSTERED 
(
[idNumeroComada] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO