CREATE TABLE [dbo].[Pedido](
   [idPedido] [int] IDENTITY(1,1) NOT NULL,
   [quantidade] [int] NULL,

CONSTRAINT [PK_Pedido] PRIMARY KEY CLUSTERED 
(
[idPedido] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO